apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: modeldeployments.llama.ai
spec:
  group: llama.ai
  names:
    kind: ModelDeployment
    plural: modeldeployments
    singular: modeldeployment
    shortNames:
    - md
  scope: Namespaced
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              modelName:
                type: string
              image:
                type: string
              replicas:
                type: integer
              weightsPVC:
                type: string
          status:
            type: object
            properties:
              readyReplicas:
                type: integer
    subresources:
      status: {}
