apiVersion: v1
kind: ServiceAccount
metadata:
  name: llama-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: llama-operator
  namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "patch", "update"]
- apiGroups: ["llama.ai"]
  resources: ["modeldeployments", "modeldeployments/status"]
  verbs: ["get", "list", "watch", "create", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: llama-operator
  namespace: default
subjects:
- kind: ServiceAccount
  name: llama-operator
  namespace: default
roleRef:
  kind: Role
  name: llama-operator
  apiGroup: rbac.authorization.k8s.io
